# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\skwor\Documents\projects\CG_test_update

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\skwor\Documents\projects\CG_test_update

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\skwor\Documents\projects\CG_test_update\CMakeFiles C:\Users\skwor\Documents\projects\CG_test_update\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\skwor\Documents\projects\CG_test_update\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P C:\Users\skwor\Documents\projects\CG_test_update\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sycl_app

# Build rule for target.
sycl_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sycl_app
.PHONY : sycl_app

# fast build rule for target.
sycl_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/build
.PHONY : sycl_app/fast

benchmark_report.obj: benchmark_report.cpp.obj
.PHONY : benchmark_report.obj

# target to build an object file
benchmark_report.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/benchmark_report.cpp.obj
.PHONY : benchmark_report.cpp.obj

benchmark_report.i: benchmark_report.cpp.i
.PHONY : benchmark_report.i

# target to preprocess a source file
benchmark_report.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/benchmark_report.cpp.i
.PHONY : benchmark_report.cpp.i

benchmark_report.s: benchmark_report.cpp.s
.PHONY : benchmark_report.s

# target to generate assembly for a file
benchmark_report.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/benchmark_report.cpp.s
.PHONY : benchmark_report.cpp.s

benchmark_runner.obj: benchmark_runner.cpp.obj
.PHONY : benchmark_runner.obj

# target to build an object file
benchmark_runner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/benchmark_runner.cpp.obj
.PHONY : benchmark_runner.cpp.obj

benchmark_runner.i: benchmark_runner.cpp.i
.PHONY : benchmark_runner.i

# target to preprocess a source file
benchmark_runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/benchmark_runner.cpp.i
.PHONY : benchmark_runner.cpp.i

benchmark_runner.s: benchmark_runner.cpp.s
.PHONY : benchmark_runner.s

# target to generate assembly for a file
benchmark_runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/benchmark_runner.cpp.s
.PHONY : benchmark_runner.cpp.s

class.obj: class.cpp.obj
.PHONY : class.obj

# target to build an object file
class.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/class.cpp.obj
.PHONY : class.cpp.obj

class.i: class.cpp.i
.PHONY : class.i

# target to preprocess a source file
class.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/class.cpp.i
.PHONY : class.cpp.i

class.s: class.cpp.s
.PHONY : class.s

# target to generate assembly for a file
class.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/class.cpp.s
.PHONY : class.cpp.s

io_utils.obj: io_utils.cpp.obj
.PHONY : io_utils.obj

# target to build an object file
io_utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/io_utils.cpp.obj
.PHONY : io_utils.cpp.obj

io_utils.i: io_utils.cpp.i
.PHONY : io_utils.i

# target to preprocess a source file
io_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/io_utils.cpp.i
.PHONY : io_utils.cpp.i

io_utils.s: io_utils.cpp.s
.PHONY : io_utils.s

# target to generate assembly for a file
io_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/io_utils.cpp.s
.PHONY : io_utils.cpp.s

launcher.obj: launcher.cpp.obj
.PHONY : launcher.obj

# target to build an object file
launcher.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/launcher.cpp.obj
.PHONY : launcher.cpp.obj

launcher.i: launcher.cpp.i
.PHONY : launcher.i

# target to preprocess a source file
launcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/launcher.cpp.i
.PHONY : launcher.cpp.i

launcher.s: launcher.cpp.s
.PHONY : launcher.s

# target to generate assembly for a file
launcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/launcher.cpp.s
.PHONY : launcher.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/main.cpp.s
.PHONY : main.cpp.s

math_operation.obj: math_operation.cpp.obj
.PHONY : math_operation.obj

# target to build an object file
math_operation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/math_operation.cpp.obj
.PHONY : math_operation.cpp.obj

math_operation.i: math_operation.cpp.i
.PHONY : math_operation.i

# target to preprocess a source file
math_operation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/math_operation.cpp.i
.PHONY : math_operation.cpp.i

math_operation.s: math_operation.cpp.s
.PHONY : math_operation.s

# target to generate assembly for a file
math_operation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/math_operation.cpp.s
.PHONY : math_operation.cpp.s

mkl_solver.obj: mkl_solver.cpp.obj
.PHONY : mkl_solver.obj

# target to build an object file
mkl_solver.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/mkl_solver.cpp.obj
.PHONY : mkl_solver.cpp.obj

mkl_solver.i: mkl_solver.cpp.i
.PHONY : mkl_solver.i

# target to preprocess a source file
mkl_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/mkl_solver.cpp.i
.PHONY : mkl_solver.cpp.i

mkl_solver.s: mkl_solver.cpp.s
.PHONY : mkl_solver.s

# target to generate assembly for a file
mkl_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/mkl_solver.cpp.s
.PHONY : mkl_solver.cpp.s

preconditioner.obj: preconditioner.cpp.obj
.PHONY : preconditioner.obj

# target to build an object file
preconditioner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/preconditioner.cpp.obj
.PHONY : preconditioner.cpp.obj

preconditioner.i: preconditioner.cpp.i
.PHONY : preconditioner.i

# target to preprocess a source file
preconditioner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/preconditioner.cpp.i
.PHONY : preconditioner.cpp.i

preconditioner.s: preconditioner.cpp.s
.PHONY : preconditioner.s

# target to generate assembly for a file
preconditioner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/preconditioner.cpp.s
.PHONY : preconditioner.cpp.s

solvers.obj: solvers.cpp.obj
.PHONY : solvers.obj

# target to build an object file
solvers.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/solvers.cpp.obj
.PHONY : solvers.cpp.obj

solvers.i: solvers.cpp.i
.PHONY : solvers.i

# target to preprocess a source file
solvers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/solvers.cpp.i
.PHONY : solvers.cpp.i

solvers.s: solvers.cpp.s
.PHONY : solvers.s

# target to generate assembly for a file
solvers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sycl_app.dir\build.make CMakeFiles/sycl_app.dir/solvers.cpp.s
.PHONY : solvers.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... sycl_app
	@echo ... benchmark_report.obj
	@echo ... benchmark_report.i
	@echo ... benchmark_report.s
	@echo ... benchmark_runner.obj
	@echo ... benchmark_runner.i
	@echo ... benchmark_runner.s
	@echo ... class.obj
	@echo ... class.i
	@echo ... class.s
	@echo ... io_utils.obj
	@echo ... io_utils.i
	@echo ... io_utils.s
	@echo ... launcher.obj
	@echo ... launcher.i
	@echo ... launcher.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... math_operation.obj
	@echo ... math_operation.i
	@echo ... math_operation.s
	@echo ... mkl_solver.obj
	@echo ... mkl_solver.i
	@echo ... mkl_solver.s
	@echo ... preconditioner.obj
	@echo ... preconditioner.i
	@echo ... preconditioner.s
	@echo ... solvers.obj
	@echo ... solvers.i
	@echo ... solvers.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P C:\Users\skwor\Documents\projects\CG_test_update\CMakeFiles\VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

